import { notFound } from "next/navigation";
import { Stethoscope } from "lucide-react";
import { posService } from "@/modules/pos/pos.service";
import { money } from "@/core/utils/format";
import { PrintButton } from "@/components/receipts/print-button";

export default async function PosReceiptPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const sale = await posService.getSale(id);
  if (!sale) notFound();

  const items = sale.items as { name: string; priceCents: number; quantity: number }[];

  return (
    <div className="min-h-screen bg-muted/30 py-10 print:bg-white print:py-0">
      <div className="mx-auto max-w-2xl px-4">
        <div className="mb-4 flex justify-end print:hidden">
          <PrintButton />
        </div>

        <div className="rounded-xl border bg-background p-8 shadow-sm print:rounded-none print:border-0 print:shadow-none">
          <div className="flex items-start justify-between border-b pb-6">
            <div>
              <p className="flex items-center gap-2 text-xl font-bold">
                <Stethoscope className="h-6 w-6 text-primary print:hidden" />
                {sale.doctor.clinicName ?? sale.doctor.fullName}
              </p>
              <p className="mt-1 text-sm text-muted-foreground">{sale.doctor.fullName}</p>
              {sale.doctor.clinicAddress && (
                <p className="text-sm text-muted-foreground">{sale.doctor.clinicAddress}</p>
              )}
              {sale.doctor.phone && (
                <p className="text-sm text-muted-foreground">{sale.doctor.phone}</p>
              )}
            </div>
            <div className="text-right">
              <p className="text-lg font-bold">INVOICE</p>
              <p className="font-mono text-sm">{sale.saleNumber}</p>
              <p className="text-sm text-muted-foreground">
                {sale.createdAt.toISOString().slice(0, 10)}
              </p>
            </div>
          </div>

          {sale.patientName && (
            <div className="border-b py-4 text-sm">
              <span className="text-muted-foreground">Patient: </span>
              <span className="font-medium">{sale.patientName}</span>
            </div>
          )}

          <table className="w-full py-4 text-sm">
            <thead>
              <tr className="border-b text-left text-muted-foreground">
                <th className="py-3 font-medium">Item</th>
                <th className="py-3 text-center font-medium">Qty</th>
                <th className="py-3 text-right font-medium">Price</th>
                <th className="py-3 text-right font-medium">Amount</th>
              </tr>
            </thead>
            <tbody>
              {items.map((it, i) => (
                <tr key={i} className="border-b">
                  <td className="py-3">{it.name}</td>
                  <td className="py-3 text-center">{it.quantity}</td>
                  <td className="py-3 text-right">{money(it.priceCents)}</td>
                  <td className="py-3 text-right">{money(it.priceCents * it.quantity)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <div className="ml-auto mt-4 w-56 space-y-1 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Subtotal</span>
              <span>{money(sale.subtotalCents)}</span>
            </div>
            {sale.discountCents > 0 && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">Discount</span>
                <span>−{money(sale.discountCents)}</span>
              </div>
            )}
            {sale.taxCents > 0 && (
              <div className="flex justify-between">
                <span className="text-muted-foreground">Tax</span>
                <span>{money(sale.taxCents)}</span>
              </div>
            )}
            <div className="flex justify-between border-t pt-2 text-base font-bold">
              <span>Total</span>
              <span>{money(sale.totalCents)}</span>
            </div>
            <div className="flex justify-between pt-1">
              <span className="text-muted-foreground">Paid via</span>
              <span className="font-medium capitalize">{sale.paymentMethod}</span>
            </div>
          </div>

          <p className="mt-10 text-center text-sm text-muted-foreground">
            Thank you. Get well soon.
          </p>
        </div>
        <p className="mt-4 text-center text-xs text-muted-foreground print:hidden">
          Generated by ClinicBook POS · {sale.saleNumber}
        </p>
      </div>
    </div>
  );
}
